export const devices = [
  'Google Nexus 5',
  'Google Nexus 6',
  'Google Pixel 3 XL',
  'Google Pixel 3',
  'Google Pixel 4 XL',
  'Google Pixel 4',
  'iPad Air 2019',
  'iPad Mini 2019',
  'iPad Pro 11 2018',
  'iPad Pro 11 2020',
  'iPad Pro 12.9 2018',
  'iPad Pro 12.9 2020',
  'iPhone 11 Pro Max',
  'iPhone 11',
  'iPhone 6',
  'iPhone 7',
  'iPhone 8',
  'iPhone X',
  'iPhone XS',
  'Motorola Moto G7 Play',
  'OnePlus 6T',
  'OnePlus 7',
  'OnePlus 7T',
  'OnePlus 8',
  'Samsung Galaxy A10',
  'Samsung Galaxy Note 10 Plus',
  'Samsung Galaxy Note 10',
  'Samsung Galaxy Note 8',
  'Samsung Galaxy Note 9',
  'Samsung Galaxy S10 Plus',
  'Samsung Galaxy S10e',
  'Samsung Galaxy S20 Plus',
  'Samsung Galaxy S20 Ultra',
  'Samsung Galaxy S20',
  'Samsung Galaxy S7',
  'Samsung Galaxy S8 Plus',
  'Samsung Galaxy S8',
  'Samsung Galaxy S9 Plus',
  'Xiaomi Redmi Note 7',
  'Xiaomi Redmi Note 8',
];
